name: RuboCop

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        ruby-version: [head, 2.7.4, 2.6.8, 2.5.9]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1.84.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ matrix.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ matrix.os }}-rubocop-
    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle config set without 'default doc job cable storage ujs test db'
        bundle install --jobs 4 --retry 3
        bundle exec rake
        bundle exec rubocop --parallel
